<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>LothiumDB - Simple DIY ORM Library For C#</Title>
    <Authors>LothiumSolutions</Authors>
    <Description>A Simple An Easy To Use C# ORM To manage different type of database connections and datas</Description>
    <Copyright>Copyright LothiumSolutions © 2023 - Provided under the GNU General Public License v3.0</Copyright>
    <RepositoryUrl>https://github.com/AndreaSantinato/LothiumDB</RepositoryUrl>
    <PackageProjectUrl>https://github.com/AndreaSantinato/LothiumDB</PackageProjectUrl>
    <NeutralLanguage>it</NeutralLanguage>
    <PackageOutputPath></PackageOutputPath>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<Version>2.0.0.0</Version>
	<AssemblyVersion>2.0.0.0</AssemblyVersion>
	<FileVersion>2.0.0.0</FileVersion>
    <PackageReleaseNotes></PackageReleaseNotes>
    <ApplicationIcon>LothiumDB.ico</ApplicationIcon>
    <PackageIcon>LothiumDB.png</PackageIcon>
    <PackageTags>Database; Data; Base; MicrosoftSQLServer; MSSqlServer; Microsoft; SQL; SQLServer; MySql; Micro-ORM; ORM; Simple-ORM; PostgreSQL</PackageTags>
    <Company>LothiumSolutions</Company>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseUrl></PackageLicenseUrl>
    <LangVersion>12</LangVersion>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Cores\" />
    <None Remove="Microsoft.Data.SqlClient" />
    <None Remove="Data\**" />
    <None Remove="Providers\**" />
    <None Remove="Core\Interfaces\**" />
    <None Remove="Enumerations\**" />
    <None Remove="EventHandlers\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Core\LothiumObject.cs" />
    <Compile Remove="Extensions\ColumnInfo.cs" />
    <Compile Remove="Extensions\PrimaryKeyInfo.cs" />
    <Compile Remove="Extensions\TableInfo.cs" />
    <Compile Remove="Enumerations\ProviderTypes.cs" />
    <Compile Remove="Enumerations\SqlCommandHistoryTypes.cs" />
    <Compile Remove="Enumerations\SqlTypes.cs" />
    <Compile Remove="Utility\AutoQueryGenerator.cs" />
    <Compile Remove="Utility\DatabaseCommands.cs" />
    <Compile Remove="Utility\LothiumDataInfo.cs" />
    <Compile Remove="Utility\SqlLastCmdHelper.cs" />
    <Compile Remove="Core\DatabaseConnectionObject.cs" />
    <Compile Remove="Core\IDatabaseConnectionObject.cs" />
    <Compile Remove="Interfaces\IDatabaseConnectionObject.cs" />
    <Compile Remove="Data\**" />
    <Compile Remove="Providers\**" />
    <Compile Remove="Core\DatabaseTransaction.cs" />
    <Compile Remove="Core\Interfaces\IProvider.cs" />
    <Compile Remove="Core\Interfaces\IDatabaseCore.cs" />
    <Compile Remove="Core\Interfaces\**" />
    <Compile Remove="IDatabaseTransaction.cs" />
    <Compile Remove="IDatabaseCommands.cs" />
    <Compile Remove="IDatabaseConnection.cs" />
    <Compile Remove="IDatabaseExtendedCommands.cs" />
    <Compile Remove="Enumerations\**" />
    <Compile Remove="EventHandlers\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="Data\**" />
    <EmbeddedResource Remove="Providers\**" />
    <EmbeddedResource Remove="Core\Interfaces\**" />
    <EmbeddedResource Remove="Enumerations\**" />
    <EmbeddedResource Remove="EventHandlers\**" />
  </ItemGroup>
  <ItemGroup>
    <None Include="LothiumDB\LothiumDB.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
